import type { Platform, Shipper, Reservation, WaitlistItem, Worker, QuotaLog, SystemSettings } from './types';

export const platforms: Platform[] = [
  {
    id: 'p1',
    code: 'D01',
    name: 'D01卸车',
    type: 'unload',
    weightLimit: 25,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p2',
    code: 'D02',
    name: 'D02卸车',
    type: 'unload',
    weightLimit: 30,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p3',
    code: 'D03',
    name: 'D03卸车',
    type: 'unload',
    weightLimit: 20,
    status: 'maintenance',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p4',
    code: 'L01',
    name: 'L01装车',
    type: 'load',
    weightLimit: 28,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p5',
    code: 'M01',
    name: 'M01混合',
    type: 'mixed',
    weightLimit: 30,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
];

export const shippers: Shipper[] = [
  {
    id: 's1',
    name: '华润食品',
    quota: 30,
    used: 18,
    frozen: 3,
    available: 9,
  },
  {
    id: 's2',
    name: '顺丰冷链',
    quota: 25,
    used: 12,
    frozen: 2,
    available: 11,
  },
  {
    id: 's3',
    name: '京东物流',
    quota: 25,
    used: 15,
    frozen: 0,
    available: 10,
  },
  {
    id: 's4',
    name: '安能快运',
    quota: 20,
    used: 8,
    frozen: 1,
    available: 11,
  },
];

const today = '2026-06-21';

export const reservations: Reservation[] = [
  {
    id: 'r1',
    platformId: 'p1',
    shipperId: 's1',
    startTime: `${today}T08:00:00`,
    endTime: `${today}T09:30:00`,
    vehicleNo: '沪A12345',
    vehicleType: '厢式货车',
    cargoType: '食品',
    cargoWeight: 18,
    status: 'completed',
    arrivedAt: `${today}T07:55:00`,
    completedAt: `${today}T09:20:00`,
    workerIds: ['w1', 'w2'],
    createdAt: `${today}T06:00:00`,
  },
  {
    id: 'r2',
    platformId: 'p2',
    shipperId: 's2',
    startTime: `${today}T09:00:00`,
    endTime: `${today}T10:30:00`,
    vehicleNo: '沪B67890',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    cargoWeight: 22,
    status: 'loading',
    arrivedAt: `${today}T08:58:00`,
    workerIds: ['w3', 'w4'],
    createdAt: `${today}T06:30:00`,
  },
  {
    id: 'r3',
    platformId: 'p4',
    shipperId: 's3',
    startTime: `${today}T10:00:00`,
    endTime: `${today}T11:30:00`,
    vehicleNo: '沪C11111',
    vehicleType: '厢式货车',
    cargoType: '电子产品',
    cargoWeight: 15,
    status: 'confirmed',
    workerIds: ['w5', 'w6'],
    createdAt: `${today}T07:00:00`,
  },
  {
    id: 'r4',
    platformId: 'p5',
    shipperId: 's4',
    startTime: `${today}T11:00:00`,
    endTime: `${today}T12:30:00`,
    vehicleNo: '沪D22222',
    vehicleType: '平板货车',
    cargoType: '建材',
    cargoWeight: 25,
    status: 'pending',
    createdAt: `${today}T07:30:00`,
  },
  {
    id: 'r5',
    platformId: 'p1',
    shipperId: 's1',
    startTime: `${today}T13:00:00`,
    endTime: `${today}T14:30:00`,
    vehicleNo: '沪E33333',
    vehicleType: '厢式货车',
    cargoType: '食品',
    cargoWeight: 20,
    status: 'confirmed',
    workerIds: ['w1', 'w7'],
    createdAt: `${today}T08:00:00`,
  },
  {
    id: 'r6',
    platformId: 'p2',
    shipperId: 's2',
    startTime: `${today}T14:00:00`,
    endTime: `${today}T15:30:00`,
    vehicleNo: '沪F44444',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    cargoWeight: 18,
    status: 'cancelled',
    createdAt: `${today}T08:30:00`,
  },
  {
    id: 'r7',
    platformId: 'p4',
    shipperId: 's3',
    startTime: `${today}T16:00:00`,
    endTime: `${today}T17:30:00`,
    vehicleNo: '沪G55555',
    vehicleType: '厢式货车',
    cargoType: '日用品',
    cargoWeight: 22,
    status: 'pending',
    createdAt: `${today}T09:00:00`,
  },
  {
    id: 'r8',
    platformId: 'p5',
    shipperId: 's4',
    startTime: `${today}T17:00:00`,
    endTime: `${today}T18:30:00`,
    vehicleNo: '沪H66666',
    vehicleType: '平板货车',
    cargoType: '建材',
    cargoWeight: 20,
    status: 'timeout',
    createdAt: `${today}T09:30:00`,
  },
];

export const waitlist: WaitlistItem[] = [
  {
    id: 'wl1',
    shipperId: 's1',
    targetDate: today,
    priority: 1,
    vehicleNo: '沪A99999',
    vehicleType: '厢式货车',
    cargoType: '食品',
    status: 'waiting',
    createdAt: `${today}T07:00:00`,
  },
  {
    id: 'wl2',
    shipperId: 's2',
    targetDate: today,
    priority: 3,
    vehicleNo: '沪B88888',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    status: 'notified',
    notifiedAt: `${today}T09:00:00`,
    createdAt: `${today}T07:30:00`,
  },
  {
    id: 'wl3',
    shipperId: 's3',
    targetDate: today,
    priority: 5,
    vehicleNo: '沪C77777',
    vehicleType: '厢式货车',
    cargoType: '电子产品',
    status: 'converted',
    convertedReservationId: 'r3',
    createdAt: `${today}T06:45:00`,
  },
];

export const workers: Worker[] = [
  { id: 'w1', name: '张三', group: 'A', status: 'busy', todayTasks: 3 },
  { id: 'w2', name: '李四', group: 'A', status: 'idle', todayTasks: 2 },
  { id: 'w3', name: '王五', group: 'A', status: 'busy', todayTasks: 4 },
  { id: 'w4', name: '赵六', group: 'A', status: 'busy', todayTasks: 3 },
  { id: 'w5', name: '钱七', group: 'B', status: 'idle', todayTasks: 1 },
  { id: 'w6', name: '孙八', group: 'B', status: 'idle', todayTasks: 2 },
  { id: 'w7', name: '周九', group: 'B', status: 'leave', todayTasks: 0 },
  { id: 'w8', name: '吴十', group: 'B', status: 'busy', todayTasks: 5 },
];

export const quotaLogs: QuotaLog[] = [
  { id: 'ql1', shipperId: 's1', amount: 5, type: 'deduct', reservationId: 'r1', operator: 'system', createdAt: `${today}T06:00:00` },
  { id: 'ql2', shipperId: 's2', amount: 4, type: 'deduct', reservationId: 'r2', operator: 'system', createdAt: `${today}T06:30:00` },
  { id: 'ql3', shipperId: 's3', amount: 3, type: 'deduct', reservationId: 'r3', operator: 'system', createdAt: `${today}T07:00:00` },
  { id: 'ql4', shipperId: 's4', amount: 2, type: 'freeze', reservationId: 'r4', operator: 'admin', createdAt: `${today}T07:30:00` },
  { id: 'ql5', shipperId: 's1', amount: 3, type: 'freeze', reservationId: 'r5', operator: 'admin', createdAt: `${today}T08:00:00` },
  { id: 'ql6', shipperId: 's2', amount: 4, type: 'release', reservationId: 'r6', operator: 'system', createdAt: `${today}T08:30:00` },
  { id: 'ql7', shipperId: 's3', amount: 2, type: 'deduct', reservationId: 'r7', operator: 'system', createdAt: `${today}T09:00:00` },
  { id: 'ql8', shipperId: 's4', amount: 2, type: 'unfreeze', reservationId: 'r8', operator: 'admin', createdAt: `${today}T09:30:00` },
  { id: 'ql9', shipperId: 's1', amount: 2, type: 'deduct', operator: 'admin', createdAt: '2026-06-20T16:00:00' },
  { id: 'ql10', shipperId: 's2', amount: 3, type: 'release', operator: 'system', createdAt: '2026-06-20T17:00:00' },
];

export const settings: SystemSettings = {
  timeoutMinutes: 30,
  waitlistConfirmMinutes: 15,
  totalQuota: 100,
};
