import type { Platform, Shipper, Reservation, WaitlistItem, Worker, QuotaLog, SystemSettings, OperationLog, QuotaAdjustment } from './types';

export const platforms: Platform[] = [
  {
    id: 'p1',
    code: 'D01',
    name: 'D01卸车',
    type: 'unload',
    weightLimit: 25,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p2',
    code: 'D02',
    name: 'D02卸车',
    type: 'unload',
    weightLimit: 30,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p3',
    code: 'D03',
    name: 'D03卸车',
    type: 'unload',
    weightLimit: 20,
    status: 'maintenance',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p4',
    code: 'L01',
    name: 'L01装车',
    type: 'load',
    weightLimit: 28,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'p5',
    code: 'M01',
    name: 'M01混合',
    type: 'mixed',
    weightLimit: 30,
    status: 'active',
    createdAt: '2026-06-01T08:00:00Z',
  },
];

export const shippers: Shipper[] = [
  {
    id: 's1',
    name: '华润食品',
    quota: 30,
    used: 18,
    frozen: 3,
    available: 9,
  },
  {
    id: 's2',
    name: '顺丰冷链',
    quota: 25,
    used: 12,
    frozen: 2,
    available: 11,
  },
  {
    id: 's3',
    name: '京东物流',
    quota: 25,
    used: 15,
    frozen: 0,
    available: 10,
  },
  {
    id: 's4',
    name: '安能快运',
    quota: 20,
    used: 8,
    frozen: 1,
    available: 11,
  },
];

const today = '2026-06-21';

export const reservations: Reservation[] = [
  {
    id: 'r1',
    platformId: 'p1',
    shipperId: 's1',
    startTime: `${today}T08:00:00`,
    endTime: `${today}T09:30:00`,
    vehicleNo: '沪A12345',
    vehicleType: '厢式货车',
    cargoType: '食品',
    cargoWeight: 18,
    status: 'completed',
    arrivedAt: `${today}T07:55:00`,
    completedAt: `${today}T09:20:00`,
    workerIds: ['w1', 'w2'],
    createdAt: `${today}T06:00:00`,
  },
  {
    id: 'r2',
    platformId: 'p2',
    shipperId: 's2',
    startTime: `${today}T09:00:00`,
    endTime: `${today}T10:30:00`,
    vehicleNo: '沪B67890',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    cargoWeight: 22,
    status: 'loading',
    arrivedAt: `${today}T08:58:00`,
    workerIds: ['w3', 'w4'],
    createdAt: `${today}T06:30:00`,
  },
  {
    id: 'r3',
    platformId: 'p4',
    shipperId: 's3',
    startTime: `${today}T10:00:00`,
    endTime: `${today}T11:30:00`,
    vehicleNo: '沪C11111',
    vehicleType: '厢式货车',
    cargoType: '电子产品',
    cargoWeight: 15,
    status: 'confirmed',
    workerIds: ['w5', 'w6'],
    createdAt: `${today}T07:00:00`,
  },
  {
    id: 'r4',
    platformId: 'p5',
    shipperId: 's4',
    startTime: `${today}T11:00:00`,
    endTime: `${today}T12:30:00`,
    vehicleNo: '沪D22222',
    vehicleType: '平板货车',
    cargoType: '建材',
    cargoWeight: 25,
    status: 'pending',
    createdAt: `${today}T07:30:00`,
  },
  {
    id: 'r5',
    platformId: 'p1',
    shipperId: 's1',
    startTime: `${today}T13:00:00`,
    endTime: `${today}T14:30:00`,
    vehicleNo: '沪E33333',
    vehicleType: '厢式货车',
    cargoType: '食品',
    cargoWeight: 20,
    status: 'confirmed',
    workerIds: ['w1', 'w7'],
    createdAt: `${today}T08:00:00`,
  },
  {
    id: 'r6',
    platformId: 'p2',
    shipperId: 's2',
    startTime: `${today}T14:00:00`,
    endTime: `${today}T15:30:00`,
    vehicleNo: '沪F44444',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    cargoWeight: 18,
    status: 'cancelled',
    createdAt: `${today}T08:30:00`,
  },
  {
    id: 'r7',
    platformId: 'p4',
    shipperId: 's3',
    startTime: `${today}T16:00:00`,
    endTime: `${today}T17:30:00`,
    vehicleNo: '沪G55555',
    vehicleType: '厢式货车',
    cargoType: '日用品',
    cargoWeight: 22,
    status: 'pending',
    createdAt: `${today}T09:00:00`,
  },
  {
    id: 'r8',
    platformId: 'p5',
    shipperId: 's4',
    startTime: `${today}T17:00:00`,
    endTime: `${today}T18:30:00`,
    vehicleNo: '沪H66666',
    vehicleType: '平板货车',
    cargoType: '建材',
    cargoWeight: 20,
    status: 'timeout',
    createdAt: `${today}T09:30:00`,
  },
];

export const waitlist: WaitlistItem[] = [
  {
    id: 'wl1',
    shipperId: 's1',
    targetDate: today,
    priority: 1,
    vehicleNo: '沪A99999',
    vehicleType: '厢式货车',
    cargoType: '食品',
    status: 'waiting',
    createdAt: `${today}T07:00:00`,
  },
  {
    id: 'wl2',
    shipperId: 's2',
    targetDate: today,
    priority: 3,
    vehicleNo: '沪B88888',
    vehicleType: '冷藏车',
    cargoType: '冷链货物',
    status: 'notified',
    notifiedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    createdAt: `${today}T07:30:00`,
  },
  {
    id: 'wl3',
    shipperId: 's3',
    targetDate: today,
    priority: 5,
    vehicleNo: '沪C77777',
    vehicleType: '厢式货车',
    cargoType: '电子产品',
    status: 'converted',
    convertedReservationId: 'r3',
    createdAt: `${today}T06:45:00`,
  },
  {
    id: 'wl4',
    shipperId: 's4',
    targetDate: today,
    priority: 2,
    vehicleNo: '沪D66666',
    vehicleType: '平板货车',
    cargoType: '建材',
    status: 'skipped',
    skipReason: '超时未确认',
    skippedAt: `${today}T08:45:00`,
    createdAt: `${today}T07:15:00`,
  },
];

export const workers: Worker[] = [
  { id: 'w1', name: '张三', group: 'A', status: 'busy', todayTasks: 3 },
  { id: 'w2', name: '李四', group: 'A', status: 'idle', todayTasks: 2 },
  { id: 'w3', name: '王五', group: 'A', status: 'busy', todayTasks: 4 },
  { id: 'w4', name: '赵六', group: 'A', status: 'busy', todayTasks: 3 },
  { id: 'w5', name: '钱七', group: 'B', status: 'idle', todayTasks: 1 },
  { id: 'w6', name: '孙八', group: 'B', status: 'idle', todayTasks: 2 },
  { id: 'w7', name: '周九', group: 'B', status: 'leave', todayTasks: 0 },
  { id: 'w8', name: '吴十', group: 'B', status: 'busy', todayTasks: 5 },
  { id: 'w9', name: '郑十一', group: 'C', status: 'idle', todayTasks: 1 },
  { id: 'w10', name: '王十二', group: 'C', status: 'busy', todayTasks: 3 },
];

export const quotaLogs: QuotaLog[] = [
  { id: 'ql1', shipperId: 's1', amount: 5, type: 'deduct', reservationId: 'r1', operator: 'system', createdAt: `${today}T06:00:00` },
  { id: 'ql2', shipperId: 's2', amount: 4, type: 'deduct', reservationId: 'r2', operator: 'system', createdAt: `${today}T06:30:00` },
  { id: 'ql3', shipperId: 's3', amount: 3, type: 'deduct', reservationId: 'r3', operator: 'system', createdAt: `${today}T07:00:00` },
  { id: 'ql4', shipperId: 's4', amount: 2, type: 'freeze', reservationId: 'r4', operator: 'admin', createdAt: `${today}T07:30:00` },
  { id: 'ql5', shipperId: 's1', amount: 3, type: 'freeze', reservationId: 'r5', operator: 'admin', createdAt: `${today}T08:00:00` },
  { id: 'ql6', shipperId: 's2', amount: 4, type: 'release', reservationId: 'r6', operator: 'system', createdAt: `${today}T08:30:00` },
  { id: 'ql7', shipperId: 's3', amount: 2, type: 'deduct', reservationId: 'r7', operator: 'system', createdAt: `${today}T09:00:00` },
  { id: 'ql8', shipperId: 's4', amount: 2, type: 'unfreeze', reservationId: 'r8', operator: 'admin', createdAt: `${today}T09:30:00` },
  { id: 'ql9', shipperId: 's1', amount: 2, type: 'deduct', operator: 'admin', createdAt: '2026-06-20T16:00:00' },
  { id: 'ql10', shipperId: 's2', amount: 3, type: 'release', operator: 'system', createdAt: '2026-06-20T17:00:00' },
  { id: 'ql11', shipperId: 's2', amount: 3, type: 'adjust', adjustmentId: 'qa2', applicant: '李经理', approver: 'admin', beforeBalance: 11, afterBalance: 14, operator: 'admin', createdAt: `${today}T10:00:00` },
  { id: 'ql12', shipperId: 's4', amount: 2, type: 'adjust', adjustmentId: 'qa4', applicant: '王主管', approver: 'admin', beforeBalance: 11, afterBalance: 13, operator: 'admin', createdAt: `${today}T10:30:00` },
];

export const operationLogs: OperationLog[] = [
  { id: 'ol1', reservationId: 'r1', action: 'create', actionLabel: '创建预约', operator: '王调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '华润食品预约D01卸车', createdAt: `${today}T06:00:00` },
  { id: 'ol2', reservationId: 'r1', action: 'assign_workers', actionLabel: '分配工人', operator: 'admin', operatorRole: 'admin', detail: '分配张三、李四', createdAt: `${today}T07:00:00` },
  { id: 'ol3', reservationId: 'r1', action: 'complete', actionLabel: '完成装卸', operator: 'system', operatorRole: 'system', beforeStatus: 'loading', afterStatus: 'completed', createdAt: `${today}T09:20:00` },

  { id: 'ol4', reservationId: 'r2', action: 'create', actionLabel: '创建预约', operator: '李调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '顺丰冷链预约D02卸车', createdAt: `${today}T06:30:00` },
  { id: 'ol5', reservationId: 'r2', action: 'confirm', actionLabel: '确认预约', operator: 'system', operatorRole: 'system', beforeStatus: 'pending', afterStatus: 'confirmed', createdAt: `${today}T07:00:00` },
  { id: 'ol6', reservationId: 'r2', action: 'start_loading', actionLabel: '开始装卸', operator: '王五', operatorRole: 'shipper', beforeStatus: 'confirmed', afterStatus: 'loading', createdAt: `${today}T09:05:00` },

  { id: 'ol7', reservationId: 'r3', action: 'create', actionLabel: '创建预约', operator: '张调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '京东物流预约L01装车', createdAt: `${today}T07:00:00` },
  { id: 'ol8', reservationId: 'r3', action: 'confirm', actionLabel: '确认预约', operator: 'admin', operatorRole: 'admin', beforeStatus: 'pending', afterStatus: 'confirmed', createdAt: `${today}T07:30:00` },
  { id: 'ol9', reservationId: 'r3', action: 'waitlist_convert', actionLabel: '候补转正式', operator: 'system', operatorRole: 'system', detail: '由候补wl3转换而来', createdAt: `${today}T07:45:00` },

  { id: 'ol10', reservationId: 'r4', action: 'create', actionLabel: '创建预约', operator: '王调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '安能快运预约M01混合', createdAt: `${today}T07:30:00` },

  { id: 'ol11', reservationId: 'r5', action: 'create', actionLabel: '创建预约', operator: '李调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '华润食品预约D01卸车', createdAt: `${today}T08:00:00` },
  { id: 'ol12', reservationId: 'r5', action: 'confirm', actionLabel: '确认预约', operator: 'admin', operatorRole: 'admin', beforeStatus: 'pending', afterStatus: 'confirmed', createdAt: `${today}T08:30:00` },

  { id: 'ol13', reservationId: 'r6', action: 'create', actionLabel: '创建预约', operator: '张调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '顺丰冷链预约D02卸车', createdAt: `${today}T08:30:00` },
  { id: 'ol14', reservationId: 'r6', action: 'cancel', actionLabel: '取消预约', operator: '李经理', operatorRole: 'shipper', beforeStatus: 'pending', afterStatus: 'cancelled', detail: '客户临时取消', createdAt: `${today}T09:00:00` },

  { id: 'ol15', reservationId: 'r7', action: 'create', actionLabel: '创建预约', operator: '王调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '京东物流预约L01装车', createdAt: `${today}T09:00:00` },

  { id: 'ol16', reservationId: 'r8', action: 'create', actionLabel: '创建预约', operator: '李调度', operatorRole: 'scheduler', beforeStatus: '', afterStatus: 'pending', detail: '安能快运预约M01混合', createdAt: `${today}T09:30:00` },
  { id: 'ol17', reservationId: 'r8', action: 'timeout', actionLabel: '超时未到', operator: 'system', operatorRole: 'system', beforeStatus: 'pending', afterStatus: 'timeout', detail: '车辆超时30分钟未到', createdAt: `${today}T10:00:00` },
];

export const quotaAdjustments: QuotaAdjustment[] = [
  {
    id: 'qa1',
    shipperId: 's1',
    type: 'increase',
    amount: 5,
    reason: '旺季补货',
    status: 'pending',
    applicant: '张经理',
    applicantRole: 'shipper',
    beforeQuota: 30,
    createdAt: `${today}T09:00:00`,
  },
  {
    id: 'qa2',
    shipperId: 's2',
    type: 'increase',
    amount: 3,
    reason: '业务增长需求',
    status: 'approved',
    applicant: '李经理',
    applicantRole: 'shipper',
    approver: 'admin',
    approverRole: 'admin',
    approvedAt: `${today}T10:00:00`,
    beforeQuota: 25,
    afterQuota: 28,
    createdAt: `${today}T09:30:00`,
  },
  {
    id: 'qa3',
    shipperId: 's3',
    type: 'decrease',
    amount: 5,
    reason: '近期爽约率高',
    status: 'rejected',
    applicant: '王主管',
    applicantRole: 'admin',
    approver: 'admin',
    approverRole: 'admin',
    rejectedAt: `${today}T09:45:00`,
    rejectReason: '需提交详细数据报告',
    beforeQuota: 25,
    createdAt: `${today}T09:15:00`,
  },
  {
    id: 'qa4',
    shipperId: 's4',
    type: 'increase',
    amount: 2,
    reason: '新客户拓展',
    status: 'approved',
    applicant: '王主管',
    applicantRole: 'shipper',
    approver: 'admin',
    approverRole: 'admin',
    approvedAt: `${today}T10:30:00`,
    beforeQuota: 20,
    afterQuota: 22,
    createdAt: `${today}T10:00:00`,
  },
];

export const settings: SystemSettings = {
  timeoutMinutes: 30,
  waitlistConfirmMinutes: 15,
  totalQuota: 100,
};
